import IptLogo from '@/components/iptLogo'
import LoginForm from '@/components/loginForm'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Left, PageContainer, Right } from '../styles/pages'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageContainer>
                <Left>
                    <IptLogo />
                </Left>
                <Right>
                    <LoginForm />
                </Right>
            </PageContainer>
        </>
    )
}

export default Home
